# Generated by Django 3.2.9 on 2021-11-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.CharField(max_length=250)),
                ('weight', models.CharField(max_length=250)),
                ('height', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('blood_type', models.CharField(max_length=250)),
                ('blood_group', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'patient_medical',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=300)),
                ('source', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'tips',
                'managed': False,
            },
        ),
    ]
